name: Publish to GitHub Pages

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  main:
    name: Build and Validate
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
      - uses: actions/upload-artifact@v4
        with:
          name: snapshots
          path: snapshot/**
      - run: git checkout gh-pages
      - uses: actions/download-artifact@v4
        with:
          name: "snapshots"
      - uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: add snapshots
