name: RDF data validation

on:
  push:
    paths:
      - '**.ttl'
      - '**.trig'
  workflow_dispatch:

jobs:
  rdf-syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: RDF syntax check
        uses: AtomGraph/RDF-syntax-check@v1.0.5
